jwt:
  key: ${JWT_KEY:secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret}
  access-token-validity-seconds: 3600000
  refresh-token-validity-seconds: 86400000
logging:
  level:
    root: info

server:
  port: 8080

spring:
  application:
    name: template-kotlin-spring-security
  datasource:
    url: jdbc:postgresql://localhost:5432/yourdatabase
    username: yourusername
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:/db/migration/{vendor}
  docker:
    compose:
      file: "./template-kotlin-spring-security/docker/compose.yml"
      lifecycle-management: start-and-stop
      skip:
        in-tests: true
  graphql:
    graphiql:
      enabled: true