version: "2.1"
services:

  springboot-multiple-datasource:
    # Using from DockerHub
    # image: abc/spring-boot-multiple-datasource
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "0.0.1-SNAPSHOT"
    ports:
      - "8088:8080"
    environment:
      MYSQL_ENDPOINT: "mysql:3306/test"
      MYSQL_ENDPOINT_OPTION: "useSSL=false"
#      CASSANDRA_ENDPOINT: "cassandra"
    depends_on:
      - mysql
#      - cassandra

  mysql:
    image: mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      MYSQL_DATABASE: test

# https://github.com/daggerok/cassandra-docker/blob/master/docker-entrypoint.sh
#  cassandra:
#    image: dschroe/cassandra-docker
#    restart: on-failure
#    ports:
#      - "7000:7000" # cluster communication
#      - "7001:7001" # cluster communication (SSL)
#      - "9042:9042" # native protocol clients
#      - "9160:9160" # thrift clients
#    volumes:
#      - ./src/main/resources/cassandra:/docker-entrypoint-initdb.d/

